version: '3.3'
services:
  app:
    restart: always
    ports:
      - 80:8080
      - 443:8080
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - back-postgresdb
    env_file:
      - .env.development
  back-postgresdb:
    restart: always
    container_name: cashmanager-postgresdb
    image: postgres:15.2-bullseye
    volumes:
      - postgres:/data/postgres
    ports:
      - '5772:5432'
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    command: postgres -c autovacuum_max_workers=6 -c autovacuum_naptime=15 -c autovacuum_vacuum_scale_factor=0.05 -c autovacuum_analyze_scale_factor=0.05
volumes:
  postgres: